### ISSUE TITLE
Vector Style Symbol - Text Rotate

### ISSUE THREAD

**Issue by fibonaki** [boundlessgeo/ol-mapbox-style#100]
I have a problem related with a label layer which has a field itself that indicates the angle of rotation. I am trying to make it work but I can't.

The example below has the style to represent the rotated labels:

[http://jsfiddle.net/8kyp19qz/8/](url)

If I delete the _"text-rotate" : "{AA_TXANG}"_ property labels are displayed with no rotation.

Could someone help me on how I should have to describe the Style configuration?

**Comment by ahocevar** [comment]
The `"text-rotate"` field does not support field tokens. What you can do is
```js
        "text-rotate": {
           "type": "identity",
           "property": "AA_TXANG"
        }
```
See https://github.com/mapbox/mapbox-gl-js/issues/873#issuecomment-303355598.
https://github.com/mapbox/mapbox-gl-js/issues/873#issuecomment-303355598
https://github.com/mapbox/mapbox-gl-js/issues/873#issuecomment-303355598
