### ISSUE TITLE
Create Vector Tile Layers Automatically

### ISSUE THREAD

**Issue by lukasmartinelli** [boundlessgeo/ol-mapbox-style#11]
For users that just want to display a Mapbox GL style JSON with `ol-mapbox-style` there could be a more convenient higher level API.

Perhaps something like this. Ideally just passing the style URL.

```js
var olms = require('ol-mapbox-style');
olms.addStyleLayer('https://raw.githubusercontent.com/openmaptiles/osm-bright-gl-style/master/style.json');
```

Would this be something that would fit into this repo? Otherwise I would put it into another repo which includes `ol-mapbox-style`.

In Maputnik right now I generate the vector sources dynamically (it is quite a hack though) for `ol-mapbox-style` but I would also like that users have this functionality when they use the style with OL3.

This would be an additional higher level API that takes care of:

- Fetching the style
- Resolving TileJSON
- Create the layer
- Create and apply the style func

**Comment by ahocevar** [comment]
I think a higher level API does make sense, but I assume you'll need to pass it at least the Mapbox Style url and an ol.Map instance.

I have thought about a higher level API as well (but haven't implemented it). I was envisioning this to be a separate library that depends on `ol-mapbox-style`. Great if you want to get that started!

**Comment by ahocevar** [comment]
I have finished a restructuring of the library. This project is now the place for a higher level API. The basic functionality has moved into https://npmjs.com/package/mapbox-to-ol-style.

**Comment by ahocevar** [comment]
I am now working on this.

**Comment by ahocevar** [comment]
Done. 13fbd1fd61bc98efaaaeb81895d333f3a39bcbcf.
