### ISSUE TITLE
cannot build olms.js due to canvas dependencies

### ISSUE THREAD

**Issue by stephanebury** [boundlessgeo/ol-mapbox-style#117]
I have a problem to build the lib.
When I do a npm install, the process is stopped to the canvas install.

C:\Users\xxx\.node-gyp\6.10.0\include\node\v8.h(19): fatal error C1083: Impossible d'ouvrir le fichier include : 'stdint.h' : No such file or directory [C:\Users\xxx\Downloads\ol-mapbox-style3.3.0\node_modules\canvas\build\binding.sln]

Could you help me please ?

thx

**Comment by ahocevar** [comment]
Please follow the instructions on https://www.npmjs.com/package/canvas, especially the linked [wiki page](https://github.com/Automattic/node-canvas/wiki/Installation:-Windows), for installing the canvas library on your machine.

**Comment by stephanebury** [comment]
There is a lot of dependencies to build canvas but with this followings line I have done the work 👍 

### configuraton python & visual


npm install --global windows-build-tools@3.1.0
npm config set python C:\Users\xxxx\.windows-build-tools\python27

npm config set msvs_version 2015


### configuration mode-gyp

npm install -g node-gyp
npm set npm_config_node_gyp "C:\Users\xxxx\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js"

node-gyp --python C:\Users\xxxx\.windows-build-tools\python27
