### ISSUE TITLE
point's fill should use ol.style.Fill

### ISSUE THREAD

**Issue by aberenyi** [boundlessgeo/ol-mapbox-style#12]
This is a quite interesting bug.

As long as I've used `ol-debug.js` it worked just fine. However, using a custom build `ol.js`, it stopped working (does not even render the layer with the basic OL styles), throwing mysterious errors to the console.

I managed to get it up and running again with this patch, but I'd like to hear what you think.

**Comment by ahocevar** [comment]
Thanks for the catch @aberenyi. Your fix makes total sense. Could you please create a pull request?
