### ISSUE TITLE
Prepare for "mapbox-gl-style-spec" package changes

### ISSUE THREAD

**Issue by lucaswoj** [boundlessgeo/ol-mapbox-style#15]
Hello! 

I work on at Mapbox on Mapbox GL. We are preparing to make some changes to the `mapbox-gl-style-spec` package which may affect you:

 - the `mapbox-gl-style-spec` package will be deprecated and replaced by `@mapbox/mapbox-gl-style-spec`
 - `mapbox-gl-style-spec` package will begin using es6 features, requiring the use of transpilation (if you're using browserify, this'll happen automatically via [bubleify](https://www.npmjs.com/package/bubleify))
 - the file structure of `mapbox-gl-style-spec` will change (which will affect the use of `require(mapbox-gl-style-spec/lib/**/*.js)`)

You can read more about these changes at https://github.com/mapbox/mapbox-gl-js/pull/3946 and https://github.com/mapbox/mapbox-gl-js/issues/3656. 

Let me know if you have any questions or need any help!

**Comment by ahocevar** [comment]
Thanks for the heads-up @lucaswoj! I'll make the required changes as soon as `@mapbox/mapbox-gl-style-spec` is published.

**Comment by ahocevar** [comment]
Done with 13fbd1fd61bc98efaaaeb81895d333f3a39bcbcf.
