### ISSUE TITLE
Usage with Tileserver GL map server

### ISSUE THREAD

**Issue by Adrien-Atmosphere** [boundlessgeo/ol-mapbox-style#18]
Hello, 
I am using Tileserver GL and/or Tileserver GL light to serve vector tiles. 
I ran into ~~two~~ an issue~~s~~ with ol-mapbox-style : 
* ~~I don't have an "access_token" in the sprite URL parameters, but I have a "style" parameter leading to malformed URL when getting sprites files ".json" and ".png". I think this can be resolved using this regex : ` var  spriteRegEx = /^(.*)(\?.*)$/; `~~
* I have an openlayers error when using apply function. I found that the URL used in processStyle (`url = glSource.url;` line 252) is in fact a TileJSON URL `http://127.0.0.1/data/planet.json` with Tileserver. The vector URL can be accessed using TileJSON URL `{"tiles":["http://127.0.0.1/data/planet/{z}/{x}/{y}.pbf"], ...}`

~~Are those~~ Is this issue~~s~~ only related to Tileserver GL? ~~Is it possible to make a patch for the first issue~~ (I was able to work around the ~~second~~ issue using applyBackground and applyStyle)?

**Comment by ahocevar** [comment]
Thanks for your feedback!

Your `spriteRegEx` looks reasonable. Could you please create a pull request?

Regarding the second issue: TileJSON urls are currently not supported by ol-mapbox-style. Would you be able and willing to create a pull request?

**Comment by Adrien-Atmosphere** [comment]
Pull request done for the first issue. 

For the second issue, I don't know what is the best solution : 
* Use Openlayers TileJSON utilities
* Fetch the urls array from the TileJSON

I think either those options will probably break compatibility with Mapbox servers. I don't have any mean to test it properly.

**Comment by ahocevar** [comment]
TileJSON is now supported, so this should be fixed.
