### ISSUE TITLE
Issue with Maputnik style

### ISSUE THREAD

**Issue by sidonaldson** [boundlessgeo/ol-mapbox-style#20]
Hi, i used [Maputnik](https://github.com/maputnik/editor) to create a new style object: `http://192.168.1.55:8080/styles/klokantech-basic.json`

I'm using webpack to bundle the source (ol 4.1.0) and try to build a map inside a react app like so:
```
this.map = new Map({target: this.map_wrapper});
apply(this.map, 'http://192.168.1.55:8080/styles/klokantech-basic.json');
```
and I get the following error
![image](https://cloud.githubusercontent.com/assets/236669/25333179/3a7ddf84-28e1-11e7-92a1-3482fcc019c2.png)

I'm a bit none-plussed about what is causing this error - any help is much appreciated!

**Comment by ahocevar** [comment]
The error comes from [pbf](https://www.npmjs.com/package/pbf) and occurs while OpenLayers is loading features from a vector tile. The reason for this error is very likely an invalid vector tile (pbf).

**Comment by sidonaldson** [comment]
I feared it might be that. I'll try to render out a simpler style to see if I get anywhere and report back. Thanks
