### ISSUE TITLE
Openlayers using ol-mapbox-style not showing street name

### ISSUE THREAD

**Issue by emperor1412** [boundlessgeo/ol-mapbox-style#23]
Hi @ahocevar , this script is a very great work, but I'm not sure if I was missed some configuration for this problem.

**Comment by ahocevar** [comment]
OpenLayers is not yet capable of rendering text along curves. This is why you do not see street names.

**Comment by emperor1412** [comment]
thanks @ahocevar , this sound disappointed. My project currently utilize openlayers a lot, this could be a show stopper to me. What a pity with openlayers.

**Comment by tds4u** [comment]
OpenLayers can handle it now !
https://github.com/openlayers/openlayers/issues/5441
https://openlayers.org/en/master/examples/street-labels.html

**Comment by costales** [comment]
Hi. I am using openlayers 4  and olms and I don't see the street names. Please, what are the requirements for showing the street names? Thanks in advance

**Comment by ahocevar** [comment]
Labels along lines were introduced in OpenLayers v4.4. This means you'd have to use ol-mapbox-style as old as v2.8 or something.

Instead of using such old versions, I would recommend upgrading to the latest version of both OpenLayers and ol-mapbox-style.

**Comment by costales** [comment]
Thanks again @ahocevar ! Updating the libraries are showing the street names. A hug
