### ISSUE TITLE
Could apply also take a parsed JSON object as argument

### ISSUE THREAD

**Issue by bartvde** [boundlessgeo/ol-mapbox-style#24]
currently apply only takes a string to a url. In my case I want to parse the JSON doc myself so I can update the redux store's state with the doc's info, and then pass on the parsed doc to ol-mapbox-style.

**Comment by ahocevar** [comment]
Good idea. Will add that.

**Comment by bartvde** [comment]
@ahocevar in hindsight, maybe exporting ```processStyle``` instead buys more flexibility and allows me to achieve the same thing, what do you think?

**Comment by bartvde** [comment]
I still need to think how can I force an update after I update the glStyle structure for a certain layer_id

**Comment by ahocevar** [comment]
I think accepting a JSON object in addition to a url string is the way to go. With a few internal changes, you should then simply be able to call `apply` again to update all layers of the supplied map.

**Comment by bartvde** [comment]
ok I will work on a PR today hopefully
