### ISSUE TITLE
AMD module

### ISSUE THREAD

**Issue by drnextgis** [boundlessgeo/ol-mapbox-style#29]
Is it possible to use this library as AMD module? Now I get erros about not found files from this section of code:

```js
if (typeof define === 'function' && define.amd) {
    define([
        "_",
        "ol/observable",
        "ol/proj",
        "ol/tilegrid",
        "ol/map",
        "ol/format/geojson",
        "ol/format/mvt",
        "ol/layer/tile",
        "ol/layer/vector",
        "ol/layer/vectortile",
        "ol/source/tilejson",
        "ol/source/vector",
        "ol/source/xyz",
        "ol/source/vectortile",
        "ol/style/style",
        "ol/style/fill",
        "ol/style/stroke",
        "ol/style/circle"
], f.bind(_g, r))
} 
```

Does it make sense to add support of passing ``ol`` object to ``ol-mapbox-style``?

**Comment by ahocevar** [comment]
You have to use `index.js`, not `dist/olms.js`.

**Comment by ahocevar** [comment]
The files referenced above are from the [ol](https://npmjs.com/package/ol) package.

**Comment by ahocevar** [comment]
Can you elaborate a bit on your setup?

**Comment by drnextgis** [comment]
I've solved my problem as described here: https://github.com/boundlessgeo/mapbox-to-ol-style/issues/16 So I think this issue can be closed.
