### ISSUE TITLE
When sprites@2x.png returns a 404, should fall back to sprites.png

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/ol-mapbox-style#30]
When rendering a mapbox style with a spritesheet on a high-resolution display, if there is no high resolution version on the spritesheet, ol-mapbox-style should fall back to using the regular spritesheet.

Current behavior is to try and read the response as a spritesheet anyways, even if a 404 is returned:

```
sprites@2x.png:1 GET http://localhost:8080/geoserver/styles/sprites@2x.png 404 ()
olms.js:193 GET http://localhost:8080/geoserver/styles/sprites@2x.json 404 ()
VM4263:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onload.xhr.onerror (olms.js:190)
```

**Comment by ahocevar** [comment]
Fixed with #31.
