### ISSUE TITLE
type background can be anywhere in the stack

### ISSUE THREAD

**Issue by bartvde** [boundlessgeo/ol-mapbox-style#36]
AFAICT from testing with mapbox GL JS it seems that the assumption we make in ```ol-mapbox-style``` is incorrect, i.e. the type background layer can be anywhere in the stack, not just at the bottom

**Comment by ahocevar** [comment]
So you mean we should not apply the background to the map container div, but create a static image layer instead?

**Comment by bartvde** [comment]
That is indeed what it means. I'm not sure if it's actually used that way, I only found out by putting some of our existing SDK examples through the mapbox GL JS renderer, and it will render the background on top of any layer that is below it. I guess it can be used to put a pattern somewhere in the stack, but hey I'm not a cartographer so just guessing here ;-)

**Comment by bartvde** [comment]
it could also be that their rendering engine processes the layer stack in the order it is, and this was just a mis-usage in our SDK examples to have background be not at the bottom of the stack. I'll see if I can get some clarification.

**Comment by bartvde** [comment]
ok this is a non-issue. I will fix up the SDK examples to use the correct sequence instead.
