### ISSUE TITLE
Zoom-based fill-opacity issue on certain zoom levels

### ISSUE THREAD

**Issue by Nikituh** [boundlessgeo/ol-mapbox-style#37]
If `fill-opacity` is zoom-based (uses `stop`s), black polygons appear instead of parks, nature reserves, buildings, towns etc. with their correct color codes.

```
"fill-opacity": {
    "stops": [
        [
            6,
            0.7
        ],
        [
            9,
            0.9
        ]
    ]
}
```

My current workaround is using a constant, then the issue does not appear:
```
"fill-opacity": 1,
```

The style I am trying to use is available at: https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json (there are several places where fill-opacity needs to be changed)

Sample javascript to reproduce the issue:
```
var baseUrl = 'https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json'; 
// var baseUrl = 'voyager.json';
var map = olms.apply('map', baseUrl);
```

Most likely culprit is **alpha interpolation**, but so far I have been unable to find the exact issue.
 
Image of issue:
<img width="1020" alt="screen shot 2017-11-23 at 15 17 29" src="https://user-images.githubusercontent.com/8685359/33174657-a3e2aff4-d061-11e7-827c-fc4dd01872df.png">

**Comment by ahocevar** [comment]
This is actually an issue in OpenLayers v4.5.0. Things should work fine if you use the latest from OpenLayers master.

**Comment by Nikituh** [comment]
Are you sure? Built master locally (`v4.5.0-35-gc48685565`), but still facing the same issues

**Comment by Nikituh** [comment]
Heh, just wrote that ol.js `v4.5.0-35-gc48685565` didn't fix it, but you beat me to it. Alright, thanks!

**Comment by Nikituh** [comment]
Reopening, as it's at least somewhat related to my previous issue.

With the current master builds, some fonts seem to be broken. It's requesting fonts that do not exist. This problem does not exist with current released builds.

Log from Chrome:
```
olms.js:7224 GET https://fonts.googleapis.com/css?family=Metropolis%7C net::ERR_ABORTED
```

_Error (400): Missing font family_ url: https://fonts.googleapis.com/css?family=Metropolis%7C

Lines 7223-7224 from compiled olms.js (Web Font Loader v1.6.28):
```
}function u(a, b, c) {
    a = a.c.getElementsByTagName(b)[0];a || (a = document.documentElement);a.insertBefore(c, a.lastChild);
```

**Comment by ahocevar** [comment]
Are you sure you have updated your dependencies? Recent releases do not use Web Font Loader any more.

**Comment by Nikituh** [comment]
Pulled most recent master and compiled again, issue seems to be fixed (mind you, I last pulled 6 days ago). Damnit, why do I keep finding bugs that have just recently been fixed.
