### ISSUE TITLE
can we use fetch instead?

### ISSUE THREAD

**Issue by bartvde** [boundlessgeo/ol-mapbox-style#41]
When writing unit tests, intercepting will be easier if we use fetch instead of XMLHttpRequest

See also: https://stackoverflow.com/questions/41706042/nock-is-intercepting-my-request-but-my-ajax-request-is-erroring-out

**Comment by bartvde** [comment]
Definitely, wanted to run the idea by you first

**Comment by ahocevar** [comment]
Fixed with #50.
