### ISSUE TITLE
build a version that includes dependencies

### ISSUE THREAD

**Issue by aidanewen** [boundlessgeo/ol-mapbox-style#48]
When I build the olms.js file using `npm install` the resulting `dist/olms.js` file doesn't work in the browser. There's lots of network errors as it tries to download `/openlayers/map.js` and a load of other missing files.

**Comment by ahocevar** [comment]
`dist/olms.js` is mostly for quick testing and meant to be an extension to OpenLayers. So you'll need `ol.js` or `ol-debug.js` from the distribution as well. You can see how that works in the [examples](https://rawgit.com/boundlessgeo/ol-mapbox-style/v2.10.1/example/index.html).

The recommended approach for production is to bundle your application with all dependencies, using e.g. Webpack or Browserify.

**Comment by aidanewen** [comment]
Thanks @ahocevar, I think the problem is that my app is currently bundled with requirejs. I add paths and a shim for `ol.js` and `olms.js` but the require statements in the browserify'd file break with requirejs.

**Comment by ahocevar** [comment]
I see. We have no plans to support requirejs with the built version. But you may have more luck with the unshimmed source (`index.js`) instead of `dist/olms.js`.

**Comment by aidanewen** [comment]
Thanks @ahocevar - appreciate your help. I'll try index.js.

**Comment by tds4u** [comment]
`npm install` is NOT creating dist/olms.js anymore?
Also `npm run doc && npm run build /scripts/ol-mapbox-style` as workaround not working as expected.
`npm run build` creates test and demo cases but no olms.js

**Comment by ahocevar** [comment]
@tds4u #80 brings back `dist/olms.js`, and it's created by `npm install` again.
