### ISSUE TITLE
"Can't resolve 'isomorphic-fetch' in path\node_modules\ol-mapbox-style"

### ISSUE THREAD

**Issue by HeercoGrond** [boundlessgeo/ol-mapbox-style#54]
Hi, I'm trying to implement a mapbox style I've made using the apply functionality. However since this errors shows up during the building during webpack, the website won't work.

Removing `import {apply} from 'ol-mapbox-style';` solves the loading, so it's an issue within the package itself. 

Environment: 
Vue.js + Webpack 3.11.0
![image](https://user-images.githubusercontent.com/21168987/37523402-1a11eb72-2927-11e8-9623-f36c18755693.png)

**Comment by HeercoGrond** [comment]
Managed to fix it by doing npm install in the folder of the package. However now my webpack build has inflated by 4mb, which is ridiculous.

**Comment by ahocevar** [comment]
I have removed the `isomorphic-fetch` requirement in 7efddd6 and published v2.10.4. Regarding the other issue, I am not sure how to reproduce. Please create a separate ticket if the issue persists with v2.10.4+.
