### ISSUE TITLE
Build with react-build fails

### ISSUE THREAD

**Issue by sylvainbeo** [boundlessgeo/ol-mapbox-style#63]
Hi,

Using this package in a react app, when i try to build for prod, i've got the following error :

`
> npm run build
>
> my-app@0.1.0 build /app/front
> react-scripts build
>
> Creating an optimized production build...
> Failed to compile.
>
> Failed to minify the code from this file: 
>
>        ./node_modules/@mapbox/mapbox-gl-style-spec/function/index.js:15 
>
`

(npm run build launch react-scripts build)

I'm trying to solve that problem. If you have any clue on what's happening. I'm not a master on npm builds.

Thanks.

**Comment by bartvde** [comment]
The docs in here: https://github.com/boundlessgeo/sdk/blob/master/docs/getting-started.md#doing-a-production-build should help you get around the issue

**Comment by sylvainbeo** [comment]
@bartvde Thank you. It helped a lot. It works now.
