### ISSUE TITLE
How about add 'resolutions' parameter  to 'applyStyle' function?

### ISSUE THREAD

**Issue by songyumeng** [boundlessgeo/ol-mapbox-style#75]
Hi, I have some vector tiles are not well displayd, I found that the reason of it is the  resolutions. My vectorTiles  ues different resolutions.
![image](https://user-images.githubusercontent.com/29563916/38122786-dd2e0888-3409-11e8-8836-97b6c71ca80f.png).

 I saw the code and found that
![image](https://user-images.githubusercontent.com/29563916/38122697-165ad43e-3409-11e8-898a-0f0665bae39c.png)
`"applyStyleFunction"` function  supports `"resolutions"`  parameter,  but  `"onchange"`  function passed `"undefined"` to it.

If possible i want to add a `"resolutions"` parameter to `"applyStyle"` function , and pass it to ` "applyStyleFunction"`

![image](https://user-images.githubusercontent.com/29563916/38126868-d94c295e-3425-11e8-9341-a4d6d41f61b5.png)

**Comment by ahocevar** [comment]
Sounds good. Please submit a pull request.
