### ISSUE TITLE
toggle multiple styles

### ISSUE THREAD

**Issue by medida** [boundlessgeo/ol-mapbox-style#77]
Hi

I'm trying to get a map to display with multiple styles of map ( street / satellite ) 
I can get the map to load with a single style... and i have also added some button which then ADD the other style. However i want the previous style to be removed.

`var satJson = 'https://maps.tilehosting.com/styles/hybrid/style.json?key=[MYKEYGOESHERE]' ;
  var styleJson = 'content/mapping/openmaptiles-street/style-basic-original.json';

   var map_view = new ol.View({
            center: ol.proj.fromLonLat([-1.0, 53]),
            zoom: 16
        })

        var map = new ol.Map({
         target: 'map',
        view: map_view
    });

   olms.apply(map, satJson);`

how would i go about toggle between the 2 styles?

Thanks

**Comment by ahocevar** [comment]
You could do something like
```js
// clear everything from previous style
map.setLayerGroup(new ol.layer.Group());
// apply new style
olms.apply(map, satJson);
```

**Comment by medida** [comment]
Thanks - Sadly this will remove all other layers like markers etc..

I've got a solution at the moment where i loop through the layers of the map and then remove the layer which is the tiles of the map. Its not pretty. 
I'll look into the groups to see if i can use this.

I can have lots of markers displayed on a map and it would be nice if the style added through apply() could be stored in its own object... Is that possible?

Thanks

**Comment by ahocevar** [comment]
We're currently working on a solution where only changes from a previous `apply()` or `applyStyle()` call will be applied to the map. This will result in what you're looking for.

In the meantime, you can loop through the existing layers and only remove those that have a `mapbox-layers` property.

**Comment by medida** [comment]
Thats sounds great - is there an approx timescale for that?

thanks

**Comment by ahocevar** [comment]
Should be done in a few weeks.

**Comment by medida** [comment]
also trying to get the mapbox-layers property.

If i'm looping through all the layers - I've looked at each object and cannot see a property matching the above.

_map_layers = map.getLayers().getArray()

_map_layers.forEach(function (_l) {
                console.log(_l)
              
            })

**Comment by ahocevar** [comment]
Try this:
```js
const layers = map.getLayers().getArray();
for (let i = layers.length - 1; i >= 0; --i) {
  const layer = layers[i];
  if (layer.get('mapbox-layers')) {
    map.removeLayer(layer);
  }
}
```

**Comment by medida** [comment]
Thanks - that's great..

Look forward to the new release as well

thanks for the quick replies.

**Comment by brightrain** [comment]
Hello @ahocevar just checking in on this toggle issue to see if the solution you mention here has been implemented. I am also trying to toggle between a 'streets' and 'imagery' layer (from map tiler) and can't seem to work out the pattern. Is your solution above still the correct approach or is there a new\better way. Thank you for your work and input.

**Comment by ahocevar** [comment]
Unfortunately this has not been implemented yet, but I may be able to get this feature funded and implemented before the end of the year.

The snipped I posted in https://github.com/openlayers/ol-mapbox-style/issues/77#issuecomment-381924958 should still work. Just call it before applying the new style to the existing map.

**Comment by brightrain** [comment]
That's exactly what I did and it works great. thx
