### ISSUE TITLE
stylefunction.js use ol.js

### ISSUE THREAD

**Issue by songyumeng** [boundlessgeo/ol-mapbox-style#78]
I saw some code in `stylefunction.js` which  must use `ol-debug.js` because `getFlatMidpoint` is not an api function.
![image](https://user-images.githubusercontent.com/29563916/38725260-569ddc40-3f39-11e8-8f93-f13b22247c8a.png)
 In `ol/geom/LineString` 
![image](https://user-images.githubusercontent.com/29563916/38727354-5bdc8552-3f3f-11e8-8ecf-da07691ec04c.png)
If possible i want to use `getCoordinateAt(0,5)` instead  of  `getFlatMidpoint()`  because `getCoordinateAt`  is an api function.

**Comment by ahocevar** [comment]
`getCoordinateAt()` is too slow, because it recalculates the coordinate with every call. Isn't it possible for you to use the ol package?

**Comment by songyumeng** [comment]
Sorry, I didn't notice `getFlatMidpoint` has a cache.
I use ol.js , neither ol package  nor ol-debug.js , and in my project `icon-image` is not displayed.
How about this , if there is `getFlatMidpoint`  function，use it，otherwise  use `getCoordinateAt(0,5)`，then all people who  use ol.js can use `image-icon` .

![image](https://user-images.githubusercontent.com/29563916/38848066-92b5e528-4237-11e8-9959-95cab5462976.png)

**Comment by ahocevar** [comment]
Most users will use the default `ol.render.Feature` tile class with vector tiles, which does not have a `getCoordinateAt()` method. I'd suggest you either use the ol package, or modify the `ol.geom.LineString` prototype to provide a `getFlatMidpoint` method, such as
```js
ol.geom.LineString.prototype.getFlatMidpoint = function() {
  return this.getCoordinateAt(0.5);
};
```
You can do this in your application before using any of ol-mapbox-style's functions.

**Comment by songyumeng** [comment]
OK.Thank you.
