### ISSUE TITLE
ol.render.Feature does not have geometry.getFlatInteriorPoint

### ISSUE THREAD

**Issue by aberenyi** [boundlessgeo/ol-mapbox-style#8]
I got an `Uncaught TypeError: geometry.getFlatInteriorPoint is not a function` unless I define `format: new ol.format.MVT({featureClass: ol.Feature})` on `ol.source.VectorTile`, which suggests that `getFlatInteriorPoint` is not defined for `ol.render.Feature` features.

Interestingly your example works just fine without `featureClass: ol.Feature`.

I'll investigate this issue further, just wanted to mention this at the first place - maybe you have a suggestion from the top of your head.

**Comment by aberenyi** [comment]
@ahocevar fast and precise resolution, as always. Many thanks 👍

**Comment by ahocevar** [comment]
In the meantime, OpenLayers 4.5 is out, which has getInteriorPoint on ol.render.Feature.

**Comment by pksorensen** [comment]
I think this is a follow up - if i wanted to show points styles for each vertex in a linestring. Should I also include those in my vector tiles? Alot of dublicate data, is it not?  atleast the geometry style for creating a multipoint feature with all vertexes is not working with ol.render.feature

**Comment by ahocevar** [comment]
> atleast the geometry style for creating a multipoint feature with all vertexes is not working with ol.render.feature

What exactly are you referring to here?

**Comment by pksorensen** [comment]
sorry,

something like this:

 var vertexstyle = new ol.style.Style({
                    image: image,
                    geometry: function (feature: ol.render.Feature) {
                        let ls = (feature.getGeometry() as ol.geom.LineString); //this do not work on vectortiles
                        console.log(ls.getGeometry());
                      
                        var coordinates =ls.getCoordinates();
                        return new ol.geom.MultiPoint(coordinates);
                    }
                });

**Comment by ahocevar** [comment]
This is an OpenLayers question. But you're right, that does not work. Is there any mapbox-style property to render each vertex of a line?

**Comment by ahocevar** [comment]
Note that you can always configure the MVT format with `featureClass: ol.Feature` to support that kind of thing.

**Comment by pksorensen** [comment]
ahh, yes - that worked. thank you
