### ISSUE TITLE
Support 'fill-pattern' parameter

### ISSUE THREAD

**Issue by songyumeng** [boundlessgeo/ol-mapbox-style#82]
Hi,Do you have plans to support 'fill-pattern' parameter?
Like  [http://openlayers.org/en/latest/examples/canvas-gradient-pattern.html?q=Pattern](http://openlayers.org/en/latest/examples/canvas-gradient-pattern.html?q=Pattern)
It is helpful for land-related maps.

**Comment by ahocevar** [comment]
It's planned, but currently without a time frame. A pull request would be welcome.
