### ISSUE TITLE
webpack Module parse failed

### ISSUE THREAD

**Issue by sdemch** [boundlessgeo/ol-mapbox-style#89]
Version    
3.0.0-beta.7 - work fine
but "ol-mapbox-style": "^3.0.0-beta.9" - generate errors

> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 ERROR  Failed to compile with 7 errors13:15:45

 error  in ./node_modules/@mapbox/mapbox-gl-style-spec/util/color.js

Module parse failed

: Unexpected token (17:5)
You may need an appropriate loader to handle this file type.
|  */
| class Color {
|     r: number;
|     g: number;
|     b: number;

 @ ./node_modules/ol-mapbox-style/index.js 23:0-60
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/OlMap/OlMap.vue
 @ ./src/components/pages/OlMap/OlMap.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?https://localhost:8080 webpack/hot/dev-server ./src/main.js

and etc. see atachment
[rr.txt](https://github.com/boundlessgeo/ol-mapbox-style/files/2115510/rr.txt)

**Comment by ahocevar** [comment]
This is not an issue with `ol-mapbox-style`. You'll need to modify your babel and/or webpack configuration to support ES2015 features like `class`. In addition, the config also needs to strip flow types (which are used by some dependencies).

For inspiration, take a look at https://github.com/boundlessgeo/ol-mapbox-style/blob/bd7581c797ed97165aa0d55a6d5e1aa7e9062b85/.babelrc and https://github.com/boundlessgeo/ol-mapbox-style/blob/b2df90a8d9f03ef0e03c1ea098b4e1beac47cbc4/webpack.config.js.

**Comment by nicky-dev** [comment]
I got same problem.

**Comment by ahocevar** [comment]
Correct. The new expression parser was introduced with v3.0.0-beta.9. Make sure you use e.g. the babel-loader or buble-loader plugin for ol-mapbox-style's dependencies.

**Comment by nicky-dev** [comment]
how to solve it. if babel version is different.

**Comment by nicky-dev** [comment]
it's work fine with this webpack config ...

![image](https://user-images.githubusercontent.com/14047941/42630989-09c42544-8603-11e8-9cf9-600030f59e3f.png)

thank you @ahocevar
