### ISSUE TITLE
Background Layer

### ISSUE THREAD

**Issue by lukasmartinelli** [boundlessgeo/ol-mapbox-style#9]
The https://www.mapbox.com/mapbox-gl-style-spec/#layers-background layer type is not supported by `ol-mapbox-style`. Is that correct?

The background stays transparent (so here instead of white, I see the black color of my HTML page).

![screenshot from 2017-01-10 12-20-24](https://cloud.githubusercontent.com/assets/1288339/21804441/4f4f741c-d72f-11e6-80e7-f5730d92e1d2.png)

**Comment by ahocevar** [comment]
This is not yet implemented. I'm working on an `applyBackground` function which will provide this functionality.

**Comment by ahocevar** [comment]
Implemented with f25e3ab0683b006421a2e9ee556df176f80a5967.

**Comment by lukasmartinelli** [comment]
> Implemented with f25e3ab.

Wow that was fast. Thanks a lot :clap:
