### ISSUE TITLE
Arcgıs vector tile - font problem

### ISSUE THREAD

**Issue by Eyyubi0614** [boundlessgeo/ol-mapbox-style#90]
Hi ,I am using olms to load arcgis style in my ol vector tile. 
I use many fonts .  some fonts can not be displayed correctly

how can i solve this problem ?

Thank You :)

**Comment by ahocevar** [comment]
OpenLayers uses browser (or web) fonts for font rendering, but the Mapbox Style format uses fonts in PBF/SDF encoding. ol-mapbox-style tries to download the font from Google Fonts. If it's not available there, you need to make sure that the map page loads all required fonts.

**Comment by Eyyubi0614** [comment]
thank you for your help. 
I prepared a vector tile in ArcGIS. I'm trying to view using the mapbox style. 
The articles on the map are displayed successfully on the ArcGIS portal. but when I use the mapbox style, I keep experiencing problems in viewing.

ArcGıs VectorTile  ===>  http://hizliresim.com/vP59Om

ol-mapbox-style  ===>  http://i.hizliresim.com/lZjlJB.jpg   

best regards

**Comment by ahocevar** [comment]
The links you provided above do not show anything. Please update them or embed the images in your comment. Also, make sure you are using v3.0.1 of ol-mapbox-style, because older versions have incorrect font handling.

**Comment by Eyyubi0614** [comment]
https://github.com/boundlessgeo/ol-mapbox-style/issues/90

2018-07-03 14:09 GMT+03:00 Andreas Hocevar <notifications@github.com>:

**Comment by Eyyubi0614** [comment]
ArcGıs VectorTile ===>  ![arcmap-vectortile](https://user-images.githubusercontent.com/24270855/42305150-470024ca-8032-11e8-80a8-33e3df028baf.JPG)



ol-mapbox-style ===> ![mapbox-vector-tile](https://user-images.githubusercontent.com/24270855/42305154-51c08fd0-8032-11e8-816a-1be7c5ec06a7.JPG)

**Comment by ahocevar** [comment]
How are you using ol-mapbox-style? If you are using the `applyStyle()` function, make sure you configure the `VectorTile` layer with `declutter: true`.  Can you share the relevant part of your code?

**Comment by Eyyubi0614** [comment]
thank you for your help.

I solved the problem.  `declutter: true` it worked

best regards

**Comment by tom62291** [comment]
> OpenLayers uses browser (or web) fonts for font rendering, but the Mapbox Style format uses fonts in PBF/SDF encoding. ol-mapbox-style tries to download the font from Google Fonts. If it's not available there, you need to make sure that the map page loads all required fonts.

Hi, do you have any coding example to load custom fonts in pbf format?

**Comment by ahocevar** [comment]
You cannot use pbf fonts with OpenLayers or ol-mapbox-style. You need to find the font in a web font format like e.g. woff2.
