### ISSUE TITLE
Applying a style with EPSG:4326 Projection

### ISSUE THREAD

**Issue by rootober** [boundlessgeo/ol-mapbox-style#98]
Hello,
I have a OL5 map using a projection of EPSG:4326. I am adding a Vector Tile layer with a projection of ESPG:4326. 

When I am using OLMS to apply a style to my Vector Tile I am seeing weird issues with how the styling is being rendered. I am assuming there is a disconnect with the Vector Tile Styling data vs the projection my map supports.

Any idea on why the below code does not seem to style the Vector Tile correctly? Is this a issue with the plugin or a issue with the way the layer is configured.

```javascript
// Create vector tile layer
var layer = new ol.layer.VectorTile({
    source: new ol.source.VectorTile({
    format: new ol.format.MVT({ featureClass: ol.render.Feature }),
   url: 'https://basemaps.arcgis.com/v1/arcgis/rest/services/World_Basemap/VectorTileServer/tile/{z}/{y}/{x}.pbf',
   projection: ol.proj.get("EPSG:4326")
   })
});
// Create map
var map = new ol.Map({
	target: 'map',
	view: new ol.View({
	   projection: 'EPSG:4326',
	   center: [0, 0],
	   zoom: 2
	}),
	layers: [layer]
});

// Get style
$.get("https://www.arcgis.com/sharing/rest/content/items/291da5eab3a0412593b66d384379f89f/resources/styles/root.json")
   .then(function(res) {
	olms.applyStyle(layer, res, "esri");
});
```
![vt](https://user-images.githubusercontent.com/40716679/45886524-59d27700-bd87-11e8-92f8-7f88acba1e42.png)

**Comment by ahocevar** [comment]
You'll have to pass the correct resolutions to the `applyStyle` function to get a correct mapping between resolutions and zoom levels:
```js
// Get style
$.get("https://www.arcgis.com/sharing/rest/content/items/291da5eab3a0412593b66d384379f89f/resources/styles/root.json")
   .then(function(res) {
	olms.applyStyle(layer, res, "esri", undefined, layer.getSource().getTileGrid().getResolutions());
});
```
See [this codesandbox](https://codesandbox.io/s/ox8390w2p5) for reference.

**Comment by rootober** [comment]
This solved the issue :) Thank you
