### ISSUE TITLE
Example VectorTile Styling Needed

### ISSUE THREAD

**Issue by fibonaki** [boundlessgeo/ol-mapbox-style#99]
Using an old version of the library I get to work mapbox styles but in a slowly way. Now, I am using the last version of this library but I don't see how I do to make it work.

I am doing something like this:

**Layer definition**
 ```
const vtLayer = new ol.layer.VectorTileLayer({
  declutter: true,
  renderMode: 'image',
  renderBuffer: 2,
  source: new ol.source.VectorTileSource({
    format: new ol.format.MVT(),
    overlaps: false,
    url: 'http://10.0.2.93:8080/geoserver/gwc/service/tms/1.0.0/bl:B_PARC@EPSG:900913@pbf/{z}/{x}/{-y}.pbf?1537872297191'
  })
});
 ```

* note that I am using my own Geoserver as a MVT server

**VT Style definition**
 ```
var stylelyrs= {
     "version": 8,
     "name": "test",
    "sources": {
      "test": {
         "type": "vector"
       }
     },
     "layers": [{
         "id": "bl:B_PARC",
         "type": "fill",
         "source": "bl:B_PARC",
         "paint": {
           "fill-color": "#00cc00",
           "fill-opacity": 0.6,
           "line-color": "#004d00",
           "line-width": 1
         }
 }]
   };
```

**Assigning style function**
```
 olms.stylefunction(vtLayer, stylelyrs, 'bl:B_PARC');
```

pbf's are loading behind but I can't see any geometry on my map, I guess it must be something related with olms applyiing style (as I said, with old version is working - getStyleFunction method). Do you know why is not working with the newest? Do you have more examples or documentation?

Thank you.

**Comment by ahocevar** [comment]
Please see https://npmjs.com/package/ol-mapbox-style for the API documentation.

Instead of `olms.stylefunction(vtLayer, stylelyrs, 'bl:B_PARC')`, you'll probably want to do
```js
import {applyStyle} from 'ol-mapbox-style';

applyStyle(vtLayer, stylelyrs, 'bl:B_PARC');
```

**Comment by fibonaki** [comment]
I have already again the documentation and I tried what you suggested to me but still is not working.

Could you please give me an example of how I could style a Vector Tile Layer instead of a GeoJSON Layer format. 

**In the API documentation says:**

```
import stylefunction from 'ol-mapbox-style/stylefunction';
// OpenLayers imports from https://npmjs.com/package/ol
import VectorLayer from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector';
import GeoJSON from 'ol/format/GeoJSON';
 
var layer = new VectorLayer({
  source: new VectorSource({
    format: new GeoJSON(),
    url: 'data/states.geojson'
  })
});
 
fetch('data/states.json').then(function(response) {
  response.json().then(function(glStyle) {
    stylefunction(layer, glStyle, 'states');
  });
});
```

**What I would like to get is:**

```
const vtLayer = new ol.layer.VectorTileLayer({
 declutter: true,
 renderMode: 'image',
 renderBuffer: 2,
 source: new ol.source.VectorTileSource({
   format: new ol.format.MVT(),
   overlaps: false,
   url: 'http://10.0.2.93:8080/geoserver/gwc/service/tms/1.0.0/bl:B_PARC@EPSG:900913@pbf/{z}/{x}/{-y}.pbf?1537872297191'
 })
});

const stylelyrs = {
    'version': 8,
    'name': 'test',
    'sources': {
      'test': {
        'type': 'vector'
      }
    },
    'layers': [{
      'id': 'parc1',
      'type': 'fill',
      'source': 'parc1',
      'paint': {
        'fill-color': '#00ff00',
        'fill-opacity': 1
      }
    },
    {
      'id': 'parc2',
      'type': 'line',
      'source': 'parc2',
      'paint': {
        'line-color': '#ff0000',
        'line-width': 0.2
      }
    }
    ]
  };

  stylefunction(vtLayer, stylelyrs, 'parc2');
  map.addLayer(vtLayer);
```


If I change my Vector Tile Layer into a GeoJSON format, this is working (but it is not what I would like to get, VectorTile will give a better performance I think).

**Comment by ahocevar** [comment]
Please see the examples in the [`example/`](https://github.com/boundlessgeo/ol-mapbox-style/tree/master/example) folder.

**Comment by ahocevar** [comment]
Your style document is quite incomplete. As a bare minimum, you need to set the `source-layer` property for the vectortile source, i.e. `'B_MANZ'` in your case. See my updated fiddle: http://jsfiddle.net/8kyp19qz/5/.
